### ISSUE TITLE
Passing empty strings to string operators throws

### ISSUE THREAD

**Issue by queil** [queil/yzl#10]
Repro:

```
"test" .= !| "" |> Yzl.render;;
System.ArgumentException: The input sequence was empty. (Parameter 'source')
   at Microsoft.FSharp.Collections.SeqModule.Head[T](IEnumerable`1 source) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 1375
   at Yzl.Core.Yzl.normalizeIndent@164(RenderOptions opts, String tab, String indent, String s)
   at Yzl.Core.Yzl.stringScalar@192(RenderOptions opts, String tab, String indent, Str _arg3)
   at Yzl.Core.Yzl.render@162(RenderOptions opts, String tab, StringBuilder builder, String indent, Node this, Node parent)
   at Yzl.Core.Yzl.mapElem@233.Invoke(Int32 i, NamedNode m)
   at Microsoft.FSharp.Collections.SeqModule.IterateIndexed[T](FSharpFunc`2 action, IEnumerable`1 source) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 523
   at Yzl.Core.Yzl.render@162(RenderOptions opts, String tab, StringBuilder builder, String indent, Node this, Node parent)
   at Yzl.Core.Yzl.renderYaml(RenderOptions opts, Node yaml)
   at <StartupCode$FSI_0006>.$FSI_0006.main@() in /Users/kris/stdin:line 8
Stopped due to error
```

**Comment by queil** [comment]
After the fix it renders an empty line instead.
